### ISSUE TITLE
Whitelist blocks website listed in "approved" list

### ISSUE THREAD

**Issue by GUTHTIRE** [unindented/whitelist-chrome#11]
Unable to access one site which is listed on the whitelist. Trying to access https://www.advancecommercial.com, tried various formats (advancecommercial.*. advancecommercial.com/*) to no avail. Not sure why it's being blocked. Help!

**Comment by unindented** [comment]
Can you post a screenshot of your config?

**Comment by GUTHTIRE** [comment]
![whitelist](https://cloud.githubusercontent.com/assets/15889445/11221304/7349fee8-8d32-11e5-86ef-2f42057b3343.jpg)

**Comment by GUTHTIRE** [comment]
Not sure if that's what you were looking for as far as config.

**Comment by unindented** [comment]
Yup, that's what I was looking for.

Try removing the existing entry and adding `advancecommercial.com` (without `https://www` at the beginning).

**Comment by GUTHTIRE** [comment]
That was what I had in there originally and it didn't work. The URL is: https://www.advancecommercial.com/webapp/wcs/stores/servlet/CWSVehicleSelectionView?catalogId=10051&langId=-1&storeId=10151&krypto=bQ1LNsinP1Yzp4QnAWw1wzTGrrvAalqMu7cjHdtaH32v2qTBo31XOr9X4ijcdOAogZKHH1ELDff%2FNWdkjLYPvwQ%2F7u3rU9PHiBT8b4SfNf9c56jp1zG7XTywQEzgfxgxoZewiITLVtEOQqm2GVSJXPNL1QiAFELeSMvJrYxH0bYwILTkH3fQ2CEQdCaR3Yz5wnBDbXryBfQdqbucR%2FmYerNCFpYKUfhEx6Qv4CLrNDBIqKFm1pji4uylp2K50UTP7Eb5aWK%2FVzWBV7ZrBkFIfppIS1Yqxr8NouowcM%2F7DJFyKRFFFSs1LpED%2FG929vk8OhJnxSGFw1j3Qin4nU1XoAt9grIJnYrKC92LDj9qTpS2Esj1zCk7Df%2FL%2FLS%2FWyRnoH0BnGZZjIyhnTgB220TqtHV4aIHqnSG0QnqC762lrgUIj%2FvDrj0dZeqc4szLXiu6mA1SDt55fw5L13ThThBPba%2F7OABiigUMKDFXDVz9cRts87s03zlqMG%2BhYWrYsvMwXpUOAMWGOofOHQEdKpkoPVdtfkBkXOXOv6wU4piOgZQxQsc9aGDqrADtMkfEjDvf4eir0aNfqalgXtpx7c8Yod36EAoYz9SfHHmoaQ5bCQguGQtRpYS6O6%2B8oxS7EvbX2irVJkcyHaOKtmrAWwNlg%3D%3D

Not sure if it tries to go somewhere else after this and that's what's causing the problem or not. Is there a way to trace URL's?

**Comment by GUTHTIRE** [comment]
sorry, closed by mistake.

**Comment by GUTHTIRE** [comment]
We cheated and recorded the browser's command line with a cellphone. It flashes too fast to see,  capturing it with the cellphone did the trick. We entered the secondary URL in the whitelist config as well and SHAZAM, that worked! Thanks for your assistance.

**Comment by unindented** [comment]
Ah nice! Glad you worked it out! 👏
