### ISSUE TITLE
Install extension to all users Windows 7

### ISSUE THREAD

**Issue by icastilloblanco** [unindented/whitelist-chrome#7]
hello. I downloaded whitelist and it works great , but I need to know how to install and run for all Windows users open the chrome

Regards

**Comment by unindented** [comment]
I don't know of a way to force all Windows users to install a certain Chrome extension. You should probably check with your system administrators.

**Comment by icastilloblanco** [comment]
Ok, thanks

**Comment by littlemissybird** [comment]
Hey  - sorry to resurrect the thread but Google has released a Group Policy template through Chromium. [https://www.chromium.org/administrators/policy-templates] 

There is an option to force install extensions but it requires the Update Manifest XML document as described at https://developer.chrome.com/extensions/autoupdate.

Hoping you can point me to where I might find that or if it's necessary for you app [ie If you publish using the Chrome Developer Dashboard.]

**Comment by unindented** [comment]
@littlemissybird no action needed on my part then?
