### ISSUE TITLE
Allowing an extension on supervised user

### ISSUE THREAD

**Issue by Ironhandz** [unindented/whitelist-chrome#8]
Howdy,

I have been using WFC on a few systems and have been enjoying the supervised user feature. I am wondering if there is any way i can allow a supervised user to have an extension working ie.: Google docs. As an example when i create a supervised user it is then unable to use features in google docs (copy/paste etc.).

Thanks!

**Comment by unindented** [comment]
If you are talking about Chrome OS's "supervised users" feature (i.e. what is described in this article: http://www.omgchrome.com/a-parents-guide-to-supervised-users/), then you are not using my extension, but a feature built into Chrome OS.
